/* $Id$ */

/*
 * Copyright (c) 2007 Regents of the University of California
 *
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *     * Redistributions of source code must retain the above copyright notice,
 *       this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of the University of California, Berkeley nor the
 *       names of its contributors may be used to endorse or promote products
 *       derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 * NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

package edu.berkeley.compbio.ml.strings;

import edu.berkeley.compbio.ml.cluster.AdditiveClusterable;

import java.util.Arrays;

/**
 * Represents the counts of a set of given patterns appearing in a string.  Typically the patterns counted are simply
 * all subsequences up to a length K.  How the symbols are interpreted and counted is up to the implementation and the
 * associated KcountScanner, so it's easy for instance to make optimized scanners for certain kinds of sequences, or to
 * use compressed alphabets, and so forth.
 * <p/>
 * Kcounts may be related through a "parent" link.  The interpretation depends on the implementation, but a typical
 * usage would be for the "parent" Kcount to contain less-specific information, i.e. fewer counts of more general
 * patterns, perhaps generated by aggregating the specific counts from the child.
 * <p/>
 * ("Parent" may not be the best name for this... perhaps "generalized" or some such?)
 *
 * @author David Soergel
 * @version $Id$
 */
public abstract class Kcount<T extends Kcount> implements AdditiveClusterable<T>, SequenceSpectrum<T>
	{
	// ------------------------------ FIELDS ------------------------------

	protected int k;
	protected int numberOfBins;
	protected int[] counts;
	protected int length;

	protected Kcount parent = null;


	// --------------------------- CONSTRUCTORS ---------------------------

	/**
	 * Creates a new Kcount instance.
	 */
	public Kcount()
		{
		}

	// --------------------- GETTER / SETTER METHODS ---------------------

	/**
	 * Returns an array of the counts.  The mapping of patterns to array indices is implementation-dependent.  A typical
	 * implementation will order all possible patterns up to length K in lexical order according to the symbol alphabet.
	 *
	 * @return The array of counts
	 */
	public int[] getCounts()
		{
		return counts;
		}

	/**
	 * Returns the pattern length K that this Kcount handles (i.e. the number of symbols per word being counted)
	 *
	 * @return the pattern length
	 */
	public int getK()
		{
		return k;
		}

	/**
	 * Returns the length of the sequence that was scanned to produce this Kcount.  This number may be greater than that
	 * given by {@link #getNumberOfSamples()} because every symbol is not necessarily counted as a sample, depending on the
	 * implementation.
	 *
	 * @return the length (type int) of this Kcount object.
	 * @see #addUnknown()
	 */
	public int getLength()
		{
		return length;
		}

	/**
	 * Returns the number of bins, which is the number of possible patterns in this Kcount.  Typically this will the
	 * alphabet size to the power of K.  Assuming a straightforward implementation, this will equal getCounts().size().
	 *
	 * @return The number of bins
	 */
	public int getNumberOfBins()
		{
		return numberOfBins;
		}

	/**
	 * Returns the parent of this Kcount.
	 *
	 * @return the parent of this Kcount.
	 */
	public Kcount getParent()// aggregateUp()
		{
		if (k == 0)
			{
			return null;
			}
		if (parent == null)
			{
			newParent();
			}
		return parent;
		}

	/**
	 * Generates a new Kcount based on this one and stores it as the parent
	 */
	protected abstract void newParent();


	// ------------------------ CANONICAL METHODS ------------------------

	/**
	 * Clone this object.  Should behave like {@link Object#clone()} except that it returns an appropriate type and so
	 * requires no cast.  Also, we insist that is method be implemented in inheriting classes, so it does not throw
	 * CloneNotSupportedException.
	 *
	 * @return a clone of this instance.
	 * @see Object#clone
	 * @see java.lang.Cloneable
	 */
	public abstract T clone();


	// ------------------------ INTERFACE METHODS ------------------------


	// --------------------- Interface AdditiveClusterable ---------------------

	/**
	 * updates this object by subtracting another one from it.
	 *
	 * @param object the object to subtract from this one
	 */
	public abstract void decrementBy(T object);

	/**
	 * updates this object by adding another one to it.
	 *
	 * @param object the object to add to this one
	 */
	public abstract void incrementBy(T object);

	/**
	 * Returns a new object representing the difference between this one and the given argument.
	 *
	 * @param object the object to be subtracted from this one
	 * @return the difference between this object and the argument
	 */
	public T minus(T object)
		{
		T result = clone();
		result.decrementBy(object);
		//result.getMetadata().setSequenceName("minus result");
		return result;
		}

	/**
	 * Returns a new object representing the sum of this one and the given argument.
	 *
	 * @param object the object to be added to this one
	 * @return the sum of this object and the argument
	 */
	public T plus(T object)
		{
		T result = clone();
		result.incrementBy(object);
		//result.getMetadata().setSequenceName("plus result");
		return result;
		}

	// --------------------- Interface Clusterable ---------------------

	/**
	 * Test whether the given pattern counts are equal to those stored here.  Differs from equals() in that implementations
	 * of this interface may contain additional state which make them not strictly equal; here we're only interested in
	 * whether they're equal as far as this interface is concerned.
	 *
	 * @param other The Kcount to compare against
	 * @return True if they are equivalent, false otherwise
	 */
	public boolean equalValue(T other)
		{
		return Arrays.equals(counts, other.counts);
		}

	// --------------------- Interface SequenceSpectrum ---------------------

	/**
	 * Returns the number of samples, which equals the sum of the counts.
	 *
	 * @return The number of samples
	 */
	public abstract int getNumberOfSamples();

	/*		{
	   if (numberOfBins == 1)
		   {
		   return counts[0];
		   }
	   return getParent().getNumberOfSamples() - getLastWords().size();// due to last word
	   }*/

	//	public abstract List<Integer> getLastWords();

	/**
	 * Test whether the given sequence statistics are equivalent to this one.  Differs from equals() in that
	 * implementations of this interface may contain additional state which make them not strictly equal; here we're only
	 * interested in whether they're equal as far as this interface is concerned.  Equivalent to {@link
	 * #equalValue(Kcount)} in this case.
	 *
	 * @param spectrum the SequenceSpectrum
	 * @return the boolean
	 */
	public boolean spectrumEquals(SequenceSpectrum spectrum)
		{
		return equalValue((T) spectrum);
		}

	// -------------------------- OTHER METHODS --------------------------

	/**
	 * Adds an "unknown" sample to this kcount, indicating that a character was consumed without incrementing any counter.
	 */
	public void addUnknown()
		{
		//metadata.length++;//incrementLength();
		length++;
		}

	/**
	 * Recursively generalize thisKcount, creating a chain of "parents" until no further generalization is possible
	 */
	protected void ensureAllParentsExist()
		{
		Kcount kc = getParent();
		if (kc != null)
			{
			kc.ensureAllParentsExist();
			}
		}

	public abstract int idForSequence(byte[] seq);

	public abstract byte[] sequenceForId(int i);

	public abstract byte[] prefixForId(int id);

	public abstract int prefixId(int id);

	public abstract int suffixId(int id);

	public abstract byte lastSymbolForId(int id);

	}
